/**
 * Copyright (c) 2019 BITPlan GmbH
 *
 * http://www.bitplan.com
 *
 * This file is part of the Opensource project at:
 * https://github.com/BITPlan/com.bitplan.evchargelog
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.bitplan.evchargelog.resources;

import java.security.Principal;
import java.util.Map;

import javax.ws.rs.core.Context;
import javax.ws.rs.core.SecurityContext;

import com.bitplan.persistence.Manager;
import com.bitplan.rest.resources.BaseResource;
import com.bitplan.rest.resources.TemplateResource;

/**
 * base class for NonOlet content
 * @author wf
 *
 * @param <MT>
 * @param <T>
 */
public class EVChargeLogResource <MT extends Manager<MT,T>,T> extends BaseResource<MT,T> {
 
  public static Principal currentUser;
  
  public static void setDebug(boolean debug) {
    TemplateResource.debug=debug;
  }
  
  /**
   * prepare the root Map
   * @param title
   */
  public static void prepareMap(Map<String,Object> rootMap,String title) {
    rootMap.put("title", title);
    rootMap.put("tooltip", "Home");
    // TODO - add link to opensource URL
    rootMap.put("comment",
        "This page is generated by the com.bitplan.evchargetrack RESTful solution for electric car charge tracking. ");
  }
  
  /**
   * prepare the root map with the given title
   * @param title
   */
  public void prepareRootMap(String title) {
	  prepareMap(rootMap,title);
  }
}
